apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ../backend-ingress.yaml

# 공통 레이블 설정
commonLabels:
  app.kubernetes.io/part-of: codecooking
  app.kubernetes.io/component: backend
  app.kubernetes.io/name: workflow
