apiVersion: v1
kind: Service
metadata:
  name: codecooking-workflow
  namespace: codecooking
  labels:
    app: codecooking-workflow
    app.kubernetes.io/part-of: codecooking
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: codecooking-workflow
