apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codecooking-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dg0ne/codecooking-gitops.git
    targetRevision: HEAD
    path: app/frontend  # 이 부분을 frontend에서 app/frontend로 변경.
  destination:
    server: https://kubernetes.default.svc
    namespace: codecooking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
