apiVersion: apps/v1
kind: Deployment
metadata:
  name: codecooking-backend-mcp
  namespace: codecooking
  labels:
    app: codecooking-backend-mcp
    app.kubernetes.io/part-of: codecooking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codecooking-backend-mcp
  template:
    metadata:
      labels:
        app: codecooking-backend-mcp
    spec:
      containers:
      - name: codecooking-backend-mcp
        image: acrdigitalgarage01.azurecr.io/codecooking-mcp:9
        imagePullPolicy: Always
        command:
        - "/bin/sh"
        - "-c"
        - "cd /app && python -m app.main"
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-api-keys
              key: anthropic-api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-api-keys
              key: openai-api-key
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
