apiVersion: apps/v1
kind: Deployment
metadata:
  name: codecooking-cicdflow
  namespace: codecooking
  labels:
    app: codecooking-cicdflow
    app.kubernetes.io/part-of: codecooking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codecooking-cicdflow
  template:
    metadata:
      labels:
        app: codecooking-cicdflow
    spec:
      containers:
      - name: codecooking-cicdflow
        image: acrdigitalgarage01.azurecr.io/codecooking-cicdflow:19
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "validate"
