apiVersion: v1
kind: Service
metadata:
  name: codecooking-cicdflow
  namespace: codecooking
  labels:
    app: codecooking-cicdflow
    app.kubernetes.io/part-of: codecooking
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: codecooking-cicdflow
